### ISSUE TITLE
Will these work with Ultisnips?

### ISSUE THREAD

**Issue by Evanlec** [bonsaiben/bootstrap-snippets#3]
Would really love to have some bootstrap snippets! These are the only ones I've found so far (though havent really looked much).

I know that most snipmate snippets are compatible with UltiSnips so I would think this should work.

**Comment by Evanlec** [comment]
I've installed these and they appear to work with UltiSnips just fine!
Anyone had any issues?
Thanks Bonsaiben for the great work

**Comment by bonsaiben** [comment]
That's great, thanks for testing.
